services:
  scheduler:
    build: .
    environment:
      - PYTHONPATH=.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/verona/verona.sock:/run/verona/verona.sock

    network_mode: "host"