version: '3.8'

services:
  git-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9418:9418" # Git server port
      - "8000:8000" # Websocket listener port
    volumes:
      - ./store:/app/store # Persist git repositories
      - ./services:/app/services # Persist services
    entrypoint: ./entrypoint.sh